### ISSUE TITLE
 Error: Cannot find module 'package.json'

### ISSUE THREAD

**Issue by octalmage** [juliangruber/require-recompile#11]
Hi there! 

I'm trying out this module and I'm running into an issue. require-rebuild seems to work when RobotJS is included as a module, but if I'm in the RobotJS directory and I run npm test or node index.js I get the error below. Note this is when there is a module mismatch. 

```
$ npm test

> robotjs@0.4.2 test /Users/jason.stallings/Documents/Apps/robotjs
> node test/all.js

Recompiling ...
/Users/jason.stallings/Documents/Apps/robotjs/node_modules/require-rebuild/index.js:24
      if (!mismatchRe.test(err.message) && !winRe.test(err.message)) throw err;
                                                                     ^

Error: Cannot find module 'package.json'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Function.Module._load (/Users/jason.stallings/Documents/Apps/robotjs/node_modules/require-rebuild/index.js:22:18)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Function.Module._load (/Users/jason.stallings/Documents/Apps/robotjs/node_modules/require-rebuild/index.js:36:17)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jason.stallings/Documents/Apps/robotjs/index.js:3:15)
    at Module._compile (module.js:541:32)
npm ERR! Test failed.  See above for more details.
```

This isn't a big deal, since most users aren't going to be trying to run the RobotJS tests, but I just want to make sure that this won't cause any errors when RobotJS is out in the wild. 

Thanks!

**Comment by juliangruber** [comment]
this module should only really be used in app code, not in a module. i'll update the docs to make that clear.

but i'll also work on fixing this, because it looks like a bug still!

**Comment by juliangruber** [comment]
bug fixed in 1.2.7, thanks for reporting!

**Comment by juliangruber** [comment]
and added documentation in 1.2.8

**Comment by octalmage** [comment]
Awesome thanks!

**Comment by octalmage** [comment]
So, since you fixed this bug, why wouldn't you recommend using this in a module? I want users of my module (RobotJS) to be able to use Electron without any extra steps. Currently since I use prebuild this isn't the case. I'm just looking for an easy solution!

**Comment by juliangruber** [comment]
you could just tell them to have `require('require-rebuild')()` as the first line of their app. from a devops point of view having "maybe" compiles after deploying just feels weird, or should be strictly opt-in.
