### ISSUE TITLE
what about setting HOME and -dist-url= etc?

### ISSUE THREAD

**Issue by ralphtheninja** [juliangruber/require-recompile#3]
This line here https://github.com/juliangruber/require-rebuild/blob/master/index.js#L35

If there are no prebuilt binaries and `prebuild` falls back to building using `node-gyp`, doesn't `node-gyp` has to be told where to get the electron headers by passing in `-dist-url=https://atom.io/download/atom-shell` to `node-gyp`?

**Comment by juliangruber** [comment]
it did work without it in my tests. i wondered about that too but decided to leave this out until it causes problems

**Comment by ralphtheninja** [comment]
> it did work without it in my tests. i wondered about that too but decided to leave this out until it causes problems

I've tested the following two scenarios:
- I first had node `5.4.1` which has the same abi as electron `0.36.2` so the first prebuilt binaries `prebuild` downloaded obviously worked out of the box
- Flipped to node `4.0.0` (which is abi 46) and when doing `npm start` then `prebuild` downloads leveldown for abi version 47

I'm not sure how to test the scenario where `prebuild` fails to find any prebuilt binaries and falls back to compiling the code. Afaict, this [commit](https://github.com/mafintosh/prebuild/commit/0d1d3e527b2d695bb0f4abb6318c173532fb5d71) only involves downloading the prebuilts and doesn't contain any information around which target that should be used when trying to compile the binaries.

Know what I mean?

cc @mafintosh

**Comment by juliangruber** [comment]
you're right, I didn't test that case yet

**Comment by ralphtheninja** [comment]
We could:
- merge and release this https://github.com/Level/abstract-leveldown/pull/51
- merge this https://github.com/Level/leveldown/pull/145 and release 1.5.0

Then we would have a good real world example to test on :)

**Comment by ralphtheninja** [comment]
_or_ throw in some c-code into https://github.com/ralphtheninja/a-native-module and use that for testing, just a thought

**Comment by juliangruber** [comment]
if we add a js api to prebuild, it will just use the right versions of everything to compile. i'll work on a pr

**Comment by ralphtheninja** [comment]
> if we add a js api to prebuild, it will just use the right versions of everything to compile. i'll work on a pr

Aaah instead of using `child_process.spawnSync()` you mean? :rocket:

**Comment by ralphtheninja** [comment]
I thought about making a js api before, in case someone wanted to require it. Seems now is the time ;)

**Comment by juliangruber** [comment]
yes exactly. i'll have a pull request up today

**Comment by ralphtheninja** [comment]
> yes exactly. i'll have a pull request up today

I guess that js api has to be sync? (Observation from @mafintosh).

**Comment by juliangruber** [comment]
damn, i didn't think of that. i'm quite sure though there is a module that can make arbitrary async code run sync.

**Comment by juliangruber** [comment]
ok, this unfortunately won't work. we can still merge the api pull request but it won't be needed for this

**Comment by juliangruber** [comment]
I set up a new repo containing the leveldown source tree, and it worked using prebuild (as it should), now i need to create another repo that just uses node-gyp and test with that

**Comment by ralphtheninja** [comment]
> I set up a new repo containing the leveldown source tree, and it worked using prebuild (as it should), now i need to create another repo that just uses node-gyp and test with that

:+1: 

> ok, this unfortunately won't work. we can still merge the api pull request but it won't be needed for this

It's good to have an api either way.

**Comment by ralphtheninja** [comment]
@juliangruber Mind if I continue hacking on the prebuild branch in the if-statement [here](https://github.com/juliangruber/require-rebuild/blob/master/index.js#L33-L38)?

**Comment by ralphtheninja** [comment]
@juliangruber How can I print out stdout from `spawnSync()` here? https://github.com/juliangruber/require-rebuild/blob/master/index.js#L33-L38

**Comment by juliangruber** [comment]
@ralphtheninja i've been thinking about this too, we have two options:
- `console.log(ps.stdout)` (not streaming)
- pass `{ stdio: 'inherit' }` to the `execSync` call, which would be nicer but _might_ just have edge cases.

I haven't worked on this yet so it would be great if you could check it out.

**Comment by juliangruber** [comment]
@ralphtheninja happily added you as a contributor :)

**Comment by ralphtheninja** [comment]
@juliangruber Cool! I tried the `{ stdio: 'inherit' }` before but couldn't get it to work. Would be best if we can stream it, but for now I just want to log things so I can see what's going on.

**Comment by ralphtheninja** [comment]
Oh wait, it works for `execSync()` but not for `spawnSync()`?

**Comment by juliangruber** [comment]
should work with spawnsync: https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options, maybe

**Comment by juliangruber** [comment]
it's still working for me with node and electron, using prebuild or not, so I'm gonna close this one
