### ISSUE TITLE
setting HOME in the node-gyp case

### ISSUE THREAD

**Issue by ralphtheninja** [juliangruber/require-recompile#7]
Is setting `HOME` below really correct? Wouldn't this mean that `node-gyp` will download headers into `~/.node-gyp/.node-gyp`?

``` js
ps = spawnSync('node-gyp', [
  'rebuild',
  '--target=' + process.versions.node
], {
  cwd: path,
  env: extend(process.env, {
    'HOME': process.env.HOME + "/.node-gyp"   
  }),
  stdio: 'inherit'
});
```

Either way, afaik it's not multi platform compatible, since windows uses `USERPROFILE` as its `HOME`.

**Comment by juliangruber** [comment]
that's what we're currently doing in level/electron-demo as well: https://github.com/Level/electron-demo/blob/master/package.json#L9

**Comment by juliangruber** [comment]
thanks for reporting! feel free to reopen if this is still not platform compatible, e.g. if we need to set other env vars as well.

**Comment by ralphtheninja** [comment]
You're still setting `HOME` for windows.

**Comment by ralphtheninja** [comment]
https://github.com/scottcorgan/home-dir/blob/master/index.js#L4

**Comment by juliangruber** [comment]
https://github.com/juliangruber/require-rebuild/pull/8
